### PR TITLE
Adstock, saturation, convolution docstring visuals

### PR DESCRIPTION
**Pull request by wd60622**
## Related Issue

- [ ] Closes issue: #
- [ ] Related issue (not closed by this PR): #
PR https://github.com/pymc-labs/pymc-marketing/pull/449  but branched off main

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [x] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
:books: Documentation preview :books:: https://pymc-marketing--461.org.readthedocs.build/en/461/

### CODE REVIEW

**Comment by wd60622** [comment]
Some are a little scrunched but here are visuals: 
Screenshot 2023-12-09 at 09 11 47
Screenshot 2023-12-09 at 09 12 08

Screenshot 2023-12-09 at 09 11 57
Screenshot 2023-12-09 at 09 12 30

Screenshot 2023-12-09 at 09 12 19

**Comment by juanitorduz** [comment]
This look great @wd60622 ! What about if we move some of the legends out of the figure? Wee for example https://stackoverflow.com/questions/4700614/how-to-put-the-legend-outside-the-plot ?

**Comment by wd60622** [comment]
> This look great @wd60622 ! What about if we move some of the legends out of the figure? Wee for example https://stackoverflow.com/questions/4700614/how-to-put-the-legend-outside-the-plot ?

Sure. Let me give those options a try

**Comment by wd60622** [comment]
Finally getting to this @juanitorduz 
I was able to fit the legends on the side. Check them out starting [here](https://pymc-marketing--461.org.readthedocs.build/en/461/api/generated/pymc_marketing.mmm.transformers.batched_convolution.html#pymc_marketing.mmm.transformers.batched_convolution)

**Review by juanitorduz — APPROVED** [review]
Thank you @wd60622 !

**Pull request merged**
