### PR TITLE
New notebook: causal inference with MMM's

### PR DESCRIPTION
**Pull request by drbenvincent**
## Description

This PR adds a new docs page which demonstrates ability to do causal inference with MMM's. In particular we showcase an example where we run a campaign with elevated media spend for a period of time. Our goal is to estimate the causal impact of the campaign. This is illustrated with simulated data in order to run a parameter recovery. So we know the true causal impact of the campaign and can therefore evaluate if the estimated causal impact is close to the true causal impact.

Overall, this notebooks showcases the ability to conduct causal inference in MMM's in `pymc-marketing`.

## Related Issue
- [ ] Partially addresses #1022

## Checklist
- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected
- [X] MMM
- [ ] CLV

## Type of change
- [ ] New feature / enhancement
- [ ] Bug fix
- [X] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--1032.org.readthedocs.build/en/1032/

### CODE REVIEW

**Comment by juanitorduz** [comment]
@drbenvincent What if we do a train test split (before and after intervention) and generate predictions and counterfactuals as https://www.pymc-marketing.io/en/latest/notebooks/mmm/mmm_time_slice_cross_validation.html ? This is how we use it in practice. WDYT?

**Comment by drbenvincent** [comment]
I will think about it. There are at least 2 scenarios:
- Using prior to an experiment to help in planning an experiment. For example, guiding you on level of spend increase for different minimum detectable effects. 
- Using after the experiment - to analyse the causal impact of a campaign. In this case I don't think there's a data leakage issue. Or are you thinking about a case where there's an unobserved confounding variable which changed at the same time as the intervention?

I'm also planning on taking about (but maybe not including a worked example) what you'd do in real work situations when you don't have counterfactual spends. That could be approached by using CausalPy & synthetic control to predict what the media spend would have been in the absence of the campaign. Though it might be the case that a company knows what they were going to spend in the absence of a campaign.

**Comment by juanitorduz** [comment]
>  I'm not sure I understand the issue with data leakage in this particular scenario. But it's been a long week.

For example, if you train in the whole data set, then you are already using information on the post-intervention period to infer parameters to generate counterfactuals.

Now that I think about it, according to https://smithamilli.com/blog/causal-ladder/ (and similar references). Your approach is indeed at the last level: counterfactuals (and fitting on the whole data is ok I think). Whereas how I would use it (for scenario planing) is on level 2: interventions. This can actually be a nice discussion to have in the notebook (if we want to)

**Comment by drbenvincent** [comment]
I understand the point now - you could argue that training on the full data may overestimate the trend. But I think that any increase in the outcome should be accounted for by the media + transformations. 

Good point about counterfactual versus interventions. I think it is worth taking about that in the notebook.

**Comment by drbenvincent** [comment]
Just to say... this notebook is going to get substantial modification / TLC. But the input already is great - looks like this topic is interesting to people 🙂

**Comment by drbenvincent** [comment]
Very excited about plans I have for this post. Though changes will have to wait until Monday. Watch this space...

**Review by wd60622 — COMMENTED** [review]
Very cool. 

Do you think we can do away with the large functions and duplication in the notebook? It seems the API should expose: 

- parameter freezing via `pm.do` instead redefining the `forward_pass`
  - Someone can initialize model without data (that defines the structure) and call something like: `params = {"intercept: 1, ...}; y = mmm.generate_target(X, params=params, target_scaler=...)`. This opens door to `X_counterfactual = some_modification(X); y_counterfactual = mmm.generate_target(X_counterfactual, params=params, ...)`
- The counterfactual comparision plot. We just need two targets, right? which we can store in xarray to have the date dim
  - `plot_counterfactual(y, y_counterfactual, along="date", intervention_date="...")`

WDYT?

**Comment by drbenvincent** [comment]
Yep - so this is the first very crude implementation. I'm trying to move away from generating synthetic data from separate numpy code and doing it with the DAG, sampling for the prior. I didn't know about `mmm.generate_target` so this is very useful. I'll see how far I get with that approach and maybe ask for some guidance. I know how to do it with base pymc, but I'm still unfamiliar with much of the pymc-marketing functionality/methods.

And I'll move towards getting counterfactual samples into the `idata.predictions` field. Is that what you're suggesting?

This notebook is going to change quite a lot before I flag as ready for review 👍🏻

**Comment by wd60622** [comment]
> Yep - so this is the first very crude implementation. I'm trying to move away from generating synthetic data from separate numpy code and doing it with the DAG, sampling for the prior. I didn't know about `mmm.generate_target` so this is very useful. I'll see how far I get with that approach and maybe ask for some guidance. I know how to do it with base pymc, but I'm still unfamiliar with much of the pymc-marketing functionality/methods.
> 
> And I'll move towards getting counterfactual samples into the `idata.predictions` field. Is that what you're suggesting?
> 
> This notebook is going to change quite a lot before I flag as ready for review 👍🏻

That doesn't exist but just some ideas are API. I think we should make whatever is useful to us

**Comment by drbenvincent** [comment]
<p>Done in an upcoming commit</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/1032/discussion/#comment-2350727880'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Have slightly modified this text. Let's see how it all reads once the larger scale structure of the notebook has settled down a bit.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/1032/discussion/#comment-2350727876'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Yep - so this initial commit was very preliminary - I've expanded on the text and narrative of the notebook much more now</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/1032/discussion/#comment-2350727906'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Good point. I've removed these and we now use default priors</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/1032/discussion/#comment-2350727910'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
Sorry, took me a moment to understand that this was a proposal @wd60622. 

> * parameter freezing via `pm.do` instead redefining the `forward_pass`
>   
>   * Someone can initialize model without data (that defines the structure) and call something like: `params = {"intercept: 1, ...}; y = mmm.generate_target(X, params=params, target_scaler=...)`. This opens door to `X_counterfactual = some_modification(X); y_counterfactual = mmm.generate_target(X_counterfactual, params=params, ...)`

Yep - I will have a go at defending these functions (quickly and crudely) in the notebook. Then they can be built out either in this PR or a different one.

> * The counterfactual comparision plot. We just need two targets, right? which we can store in xarray to have the date dim
>   
>   * `plot_counterfactual(y, y_counterfactual, along="date", intervention_date="...")`

Yes, but I think we would need a way to set the `predictions=True` flag in the kwargs of `pm.sample_posterior_predictive`. Is that possible now, or would that be new functionality.

I have to shift focus for a day or so, but I'll see what I can do code-wise in this notebook to inspire some new functionality.

**Comment by cetagostini** [comment]
<p>🚀</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/1032/discussion/#comment-2350727876'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cetagostini** [comment]
<p>🚀</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/1032/discussion/#comment-2350727906'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wd60622** [comment]
Feel free to make some issues if you don't touch in this PR

> Yes, but I think we would need a way to set the `predictions=True` flag in the kwargs of `pm.sample_posterior_predictive`. Is that possible now, or would that be new functionality.
> 
> I have to shift focus for a day or so, but I'll see what I can do code-wise in this notebook to inspire some new functionality.

The `sample_posterior_predictive` method allows for passing sample_posterior_predictive kwargs. 
My idea was to just pass the xarray.DataArray objects for a function

**Comment by drbenvincent** [comment]
Boom! Ready for review.

For iteration 1 I think it's best to leave the data simulation as it is now. But I'm more than happy to come back at a later time to generate data from an empty MMM model by sampling from the prior.

Any comments on the causal DAG? I'm not sure if I should include the time node, or whether time should also causally affect $x1$ and $x2$. The direct effect of time on sales is modelled by the trend and seasonality components - I'm thinking that can be said in text rather than be specific nodes. But happy to get thoughts on this.
Screenshot 2024-10-10 at 11 00 13

**Comment by drbenvincent** [comment]
<p>I wasn't going to add the intervention lines to the legend - it might get a bit cluttered. And I was hoping to rely on the text to make it clear that those represent the intervention period.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/1032/discussion/#comment-2408474157'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
Thanks for the review @juanitorduz. I think I've addressed most of your comments. I was going to avoid legends for the campaign interval - but if that was important I could either add them, or have it as a shaded region perhaps.

Happy to get more feedback based on this iteration.

**Comment by juanitorduz** [comment]
<p>ok! I just thought because the <code>label="intervention date"</code> which id not doing anything then </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/1032/discussion/#comment-2408474157'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by juanitorduz — APPROVED** [review]
Let's push this one out!

**Comment by cetagostini** [comment]
Hey @drbenvincent 

I'm very agree here:

>The direct effect of time on sales is modelled by the trend and seasonality components. **I'm thinking that can be said in text** 

Maybe it's a bit picky but putting time in a DAG is something I've never seen before, I've been looking a bit on the internet and I think one of the main reasons is that, time is often implicit in the temporal ordering of variables. The causal relationships are understood to occur over time without explicitly including “time” as a variable.

I think it is better to say exogenous variables and that's it, but maybe I'm incorrect 😅

**Comment by drbenvincent** [comment]
Thanks @cetagostini. What do you think @juanitorduz  about time in the DAG? I agree that you don't see it very much, but we should have _something_. I'll have a think too and edit it in a follow on PR.

**Comment by juanitorduz** [comment]
I do not have a preference. In the example notebook we use "seasonality". I think time can combine both trend and seasonality.

**Pull request merged**
