### PR TITLE
Use union of default and user provided configs in ModelBuilder

### PR DESCRIPTION
**Pull request by ricardoV94**
## Description

I don't see a good reason not to do this for the users?

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--565.org.readthedocs.build/en/565/

### CODE REVIEW

**Comment by juanitorduz** [comment]
It makes a lot of sense 😅 . There are some test failing though ....

**Comment by ricardoV94** [comment]
@juanitorduz tests are passing

**Comment by juanitorduz** [comment]
Ups!you are right! I don't know which CI I was looking then 🙈

**Review by juanitorduz — APPROVED** [review]

**Comment by ricardoV94** [comment]
> Ups!you are right! I don't know which CI I was looking then 🙈

You didn't imagine it. I had to fix a test

**Comment by juanitorduz** [comment]
Haha ok! Now everything makes sense 😄

**Pull request merged**
