### PR TITLE
MMM Example Notebook Improvement: Using `DelayedSaturatedMMM`

### PR DESCRIPTION
**Pull request by juanitorduz**
This PR improves the MMM documentation regarding the `pymc-marketing` API. The notebook focusses in the model specification and parameter recovery. We should have a more business-oriented notebook (see Robyn docs!).

Feedback is welcome!

P.S. @lucianopaz While working on this example I realised there is a bug in the step where we transform back the media contributions to the original scale. In https://github.com/pymc-labs/pymc-marketing/pull/119 and https://github.com/pymc-labs/pymc-marketing/pull/122 we rely to much ini the `inverse_transform` method. Still notice that we just need to multiply back by the scaling factor but we do not want to add the minimum of the target variable. You can test and see how the contribution shares and saturation curves are wrong. I am open for potential solutions but for now I reverted back the change in the `DelayedSaturatedMMM` and not the base class directly :)

### CODE REVIEW

**Comment by twiecki** [comment]
This is awesome!

**Comment by juanitorduz** [comment]
<p>Thanks! Corrected!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/123/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Thanks! Corrected!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/123/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>By design: x_1 should resemble a typical paid search channel and x_2 a TV spend time series. Still, no particular reason.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/123/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Yeah, for now I passed these Fourier modes as <em>control variables </em>since currently we do not have a separate seasonal component. I believe this is part of the next iteration and I will update this notebook accordingly.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/123/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
Thank you @twiecki  for the feedback! I fixed the typos and added more interpretation os the results.

**Comment by juanitorduz** [comment]
Thank you @twiecki  for the feedback! I fixed the typos and added more interpretation os the results.

**Comment by twiecki** [comment]
<p>Makes sense, maybe add that in for the uninitiated.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/123/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>done!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/123/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
🥳

**Comment by juanitorduz** [comment]
This closes https://github.com/pymc-labs/pymc-marketing/issues/24

**Pull request merged**
