### PR TITLE
Add pymc-marketing version to some MMM notebooks

### PR DESCRIPTION
**Pull request by juanitorduz**
Related to https://github.com/pymc-labs/pymc-marketing/issues/845

----
📚 Documentation preview 📚: https://pymc-marketing--907.org.readthedocs.build/en/907/

### CODE REVIEW

**Comment by wd60622** [comment]
The issue with this is that it actually isn't 0.8.0 but what will come out in the next release. I.e. it is actually always ahead of the current release, right? What are your thoughts?

**Comment by juanitorduz** [comment]
> The issue with this is that it actually isn't 0.8.0 but what will come out in the next release. I.e. it is actually always ahead of the current release, right? What are your thoughts?

I think for now we can add at least the lastest version. 

Another thing we can do is to update the version to 0.9.0dev while development

**Comment by wd60622** [comment]
> I think for now we can add at least the lastest version.

Yeah, I am fine with that

> Another thing we can do is to update the version to 0.9.0dev while development

Have something like that for this #860 
Have you done this before?

**Review by wd60622 — APPROVED** [review]
Good stuff

**Comment by juanitorduz** [comment]
Let me remove the mmm example nb from this PR as I added it in https://github.com/pymc-labs/pymc-marketing/pull/904

**Comment by juanitorduz** [comment]
> Have you done this before?

No 🙈  hehe

**Pull request merged**
