### PR TITLE
Components

### PR DESCRIPTION
**Pull request by wd60622**
Had something like this in mind @ricardoV94 

Would this break the model loading? or were you saying that changes / refactor cannot happen in the `build_model` method. 

I assumed that since the `build_model` is called after the load that any refactored code would be used. Maybe this breaks the hashing part, but I need to look into that. 

At the moment, the forward pass of the model is defined a few times which make bugs like #400 much more prone. I think pulling out large blocks like this can help: 

1. reduce the copy and paste to perform elsewhere
2. Give users another options to perform marketing specific logic within `pymc.Model` block

----
:books: Documentation preview :books:: https://pymc-marketing--404.org.readthedocs.build/en/404/

### CODE REVIEW

**Comment by wd60622** [comment]
trying to mark this as a draft

**Comment by ricardoV94** [comment]
What is the goal here, so users can call some helpers that create a bunch of model variables and deterministics directly?

If so, my question is whether that is the right level of abstraction? It looks to me as if not? I would think that if I am creating an MMM myself I would want to call the adstock/saturation myself after I have created the variables, instead of a method that expects variables to have a given name and dims, and to pass arguments via dicts?

The other thing I don't understand is the wraps stuff, but the most important thing is the design abstraction level. Do you have some examples of how you would use this?

**Comment by ricardoV94** [comment]
Regarding ModelBuilder thing this doesn't seem to pose any problems, but also doesn't make it more useable (which is fine if that's not the goal)

**Comment by wd60622** [comment]
> What is the goal here, so users can call some helpers that create a bunch of model variables and deterministics directly?
> 
> If so, my question is whether that is the right level of abstraction? It looks to me as if not? I would think that if I am creating an MMM myself I would want to call the adstock/saturation myself after I have created the variables, instead of a method that expects variables to have very specific name and dims, that must be setup via weird dicts?

The level of abstraction is fair and would interested if you have a take on this. I was just pulling out some of the pieces that are current available into what might be larger chunks. The weird dictionaries are just along for the ride based on what is written. 

If I want any customization at the moment, I would just write the whole model and mainly rely on the adstock and saturation functions

**Comment by wd60622** [comment]
> The other thing I don't understand is the wraps stuff, but the most important thing is the design abstraction level. Do you have some examples of how you would use this?

This was just to create function with the same signature. Had in mind defining the forward pass once which would handle different cases including in and outside of model context.

**Pull request closed without merging**
