### PR TITLE
Add more content to the Gamma-Gamma Notebook 

### PR DESCRIPTION
**Pull request by juanitorduz**
Similar to https://github.com/pymc-labs/pymc-marketing/pull/571.

----
📚 Documentation preview 📚: https://pymc-marketing--573.org.readthedocs.build/en/573/

### CODE REVIEW

**Comment by ricardoV94** [comment]
@juanitorduz looks great. Could you just install from conda to get rid of those ugly C-API warnings?

**Comment by juanitorduz** [comment]
> @juanitorduz looks great. Could you just install from conda to get rid of those ugly C-API warnings?

I cleaned the outputs :)

**Comment by ColtAllen** [comment]
Looking good so far. In addition to minor remarks below, it may be worth adding a practical example to illustrate (https://github.com/pymc-labs/pymc-marketing/issues/594). A synthetic monetary value column with crazy huge values like this may do the trick:

```
shape, scale = 1., 10000000. 
s = np.random.gamma(shape, scale, 1000)
```

**Comment by ColtAllen** [comment]
Also, it's an important modeling assumption that frequency and monetary value be uncorrelated (less than 0.3). Add this to a cell before the modeling section: 

`returning_customers_summary[['monetary_value', 'frequency']].corr()`

**Comment by juanitorduz** [comment]
<p>Thanks! Added</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2012359051'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I think we are "forced" by the ruff notebook style guidelines to have all the imports on top</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2012359077'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Good point! I will add it to the other notebooks as well.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2012359109'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Got it! Done!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2012359138'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>No, I suggest we leave it out and focus on our model. As you mentioned, we can reduce mentioning the <code>lifetimes</code> package. </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2012393160'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ColtAllen** [comment]
My comments were mostly related to clean up and other minor suggestions. Good work - I think this is almost ready!

**Comment by juanitorduz** [comment]
<p>hehe I do not why is it displayed like this but it looks ok on the render docs XD</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2037799466'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Right! I removed it!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2037799428'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Good catch! Thanks!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2037799509'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Good point! Added a small remark!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2037799554'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Great idea!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2037799620'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Let me skip this for now as i wanna keep this relative simple. I agree is a great point to maybe we could have a prior sensitivity analysis notebook :)</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2037799528'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I actually do not know where they are coming from. Even if I run everything in conda I still get them :(</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2037799447'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Changed the sampler params a bit and now it looks much better</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/573/discussion/#comment-2037799604'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
Thanks for the review, @ColtAllen. I think I addressed all of your comments (except the pytensor warnings I am trying to remove). Let me know what you think about this version :)

**Comment by ricardoV94** [comment]
Are you struggling to install pytensor from conda? Shouldn't be getting warnings :)

**Comment by juanitorduz** [comment]
> Are you struggling to install pytensor from conda? Shouldn't be getting warnings :)

I am using mamba because conda is too slow 🙈 . I will delete and re-create all my envs next week 🤞

**Comment by ricardoV94** [comment]
mamba/conda is the same. I also use mamba. Still you shouldn't be getting those warnings. You may not be using the right environment in the NB?

**Review by ColtAllen — APPROVED** [review]
There are a few unresolved formatting and style remarks in ReviewNB, but they're quite minor. Overall I think this is good to merge. Great work!

**Review by twiecki — APPROVED** [review]

**Pull request merged**
