### PR TITLE
Update PyMC dependency and LaTeX representation tests

### LINKED ISSUE #244: CLV LaTeX representation tests fail for pymc >= 5.3.0
When working in https://github.com/pymc-labs/pymc-marketing/pull/242, I saw the following tests failing:

```python
FAILED tests/clv/models/test_basic.py::TestCLVModel::test_repr - AssertionErr...
FAILED tests/clv/models/test_basic.py::TestCLVModel::test_process_priors - As...
FAILED tests/clv/models/test_beta_geo.py::TestBetaGeoModel::test_model_repr
FAILED tests/clv/models/test_gamma_gamma.py::TestGammaGammaModel::test_model_repr
FAILED tests/clv/models/test_gamma_gamma.py::TestGammaGammaModelIndividual::test_model_repr
FAILED tests/clv/models/test_shifted_beta_geo.py::TestShiftedBetaGeoModel::test_model_repr
```
The test do pass for previous versions.

@ricardoV94 What would be the best way to solve this so that we have backward compatibility? (do we ?)

### PR DESCRIPTION
**Pull request by larryshamalama**
Closes #244

I suspect that this should work. Let's see if tests pass

----
:books: Documentation preview :books:: https://pymc-marketing--245.org.readthedocs.build/en/245/

### CODE REVIEW

**Comment by ricardoV94** [comment]
Just update the minimum version to be the latest.

The point of testing the older is to know when it is no longer supported

**Comment by juanitorduz** [comment]
So replace https://github.com/pymc-labs/pymc-marketing/blob/main/.github/workflows/ci.yml#L10 to `5.3.0`?

**Comment by ricardoV94** [comment]
Yes, and the requirements

**Review by juanitorduz — APPROVED** [review]
🙌

**Pull request merged**
