### PR TITLE
Creating Budget Allocation Notebook Example

### PR DESCRIPTION
**Pull request by cetagostini**
Follow up documentation [PR 329](https://github.com/pymc-labs/pymc-marketing/pull/329)

----
:books: Documentation preview :books:: https://pymc-marketing--370.org.readthedocs.build/en/370/

### CODE REVIEW

**Comment by cetagostini** [comment]
<p>Totally agree, I replace the words in order to make it more timeless. Still, would like to get your input about the beginning, considering this method is very similar to used by Meta and Google, I was tempted to mention it so as not to be self-referential, but what do you think? Until now I added it as other methods to reference at the end.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/370/discussion/#comment-1697205880'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cetagostini** [comment]
<p>Modified, you're right. At first I had errors trying to do it like this, but now it worked 😅 </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/370/discussion/#comment-1697205908'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cetagostini** [comment]
<p>Agree!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/370/discussion/#comment-1697253686'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cetagostini** [comment]
<p>Added, with another references. Wait your feedback!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/370/discussion/#comment-1697253709'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
@cetagostini now that https://github.com/pymc-labs/pymc-marketing/pull/329 was merged ... do you need to update this Pr or is it ready for review?

**Pull request merged**
