### PR TITLE
Add links from CLV/MMM intros to relevant notebooks

### PR DESCRIPTION
**Pull request by cluhmann**
Closes https://github.com/pymc-labs/pymc-marketing/issues/236

----
:books: Documentation preview :books:: https://pymc-marketing--238.org.readthedocs.build/en/238/

### CODE REVIEW

**Review by ricardoV94 — COMMENTED** [review]
missing some newline at the end of file

**Comment by cluhmann** [comment]
Ok.  Links appear to be working.

**Comment by ricardoV94** [comment]
> missing some newline at the end of the guide files

This is still not fixed (check the changed files on GitHub)

**Review by ricardoV94 — APPROVED** [review]

**Comment by cluhmann** [comment]
I am going to switch to the linking scheme Ben used elsewhere in the site (pointed on in the linked issue) and see if that's cleaner. If so, then I will modify and we should be good.  If ti breaks, I will revert.

**Comment by cluhmann** [comment]
Ok. Should be good to go.

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
