### PR TITLE
Allow user to set custom constraints on the optimizer

### PR DESCRIPTION
**Pull request by wajihfabernovel**
## Related Issue

- [ ] Closes #
- [x] Related to #475 

## Checklist

- [x ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [x] MMM
- [ ] CLV

## Type of change

- [x] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--490.org.readthedocs.build/en/490/

### CODE REVIEW

**Comment by wd60622** [comment]
I suspect this should either be optional as I see many users not having access to this data. And/or the optimizer is generalized and allows a user to provide arbitrary constraints. 

Just some initial thoughts

**Comment by nialloulton** [comment]
Yeah for sure optional. In practice data on these sorts of things is very rare/not something front of mind to run in an optimization. That being said, it's a cool nice to have.

**Comment by juanitorduz** [comment]
+1 Optional

Can you add a description of the PR please?

**Comment by wajihfabernovel** [comment]
Hi there, so yeah the idea is to have it as an option for those who have external constraints that may influence the optimization of the budget allocation. I took as an example the carbon emission but it could be anything else depending on the business need. I will provide a description of the PR soon. Thank you

**Comment by ricardoV94** [comment]
IMO, this functionality should not be implemented with this level of specificity. Certainly not with new kwargs called `emissions`. 

It's fine for the method to be expanded to allow arbitrary constraints provided by the user, of which emissions would be one application.

If a general method is not feasible, then this should just be added as a documentation notebook example for users, not a library feature.

**Comment by wajihfabernovel** [comment]
I agree with you that it should be more generalised so the kwargs needs to have another name so people don't get confused about it, but it could be added as an optional kwargs so people with basic optimization and those with external constraints both can use the function to answer their needs. As for docstrings, probably i removed smthg by mistake i will review it and PR again. Thanks for your feedback

**Comment by nialloulton** [comment]
Added comments in your code, including potential suggestions to make it generic, allows for user input of custom constraints as Ricardo has mentioned. Also have given some example usage at the very bottom. - tested locally and it seems to work fine for me. @wajihfabernovel feel free to review my comments. thanks!

**Comment by twiecki** [comment]
I would say making this generic is a hard requirement. It's a great contribution that way and should only require renaming.

**Comment by ricardoV94** [comment]
> I would say making this generic is a hard requirement. It's a great contribution that way and should only require renaming.

I don't see what's hard about it? The scipy optimizer has a clear API for it, each constraint is a dictionary with some strings and a callable (this PR is just hard-coding a specific one)

**Comment by twiecki** [comment]
> > I would say making this generic is a hard requirement. It's a great contribution that way and should only require renaming.
> 
> I don't see what's hard about it? The scipy optimizer has a clear API for it, each constraint is a dictionary with some strings and a callable (this PR is just hard-coding a specific one)

I didn't mean hard as in difficult but as a strict requirement for getting this PR merged.

**Comment by ricardoV94** [comment]
@wajihfabernovel let us know if you need help with making it more general if you want to pursue than venue. More importantly, we will also need tests, and can also help with that

**Comment by twiecki** [comment]
@wajihfabernovel Are you still interested in getting this over the finish line or do you want someone else to take over?

**Comment by cetagostini** [comment]
Hey team,

> I don't see what's hard about it? The scipy optimizer has a clear API for it, each constraint is a dictionary with some strings and a callable (this PR is just hard-coding a specific one)

As I understand the goal hear is basically, allow for users to add their own constraint? Not the one we have by default?

**Comment by twiecki** [comment]
> As I understand the goal here is allow for users to add their own constraint into the optimizer? Not the one we have by default considering only the equality around maximum budget?

Yes, exactly. Let the user add extra constraints.

**Comment by wajihfabernovel** [comment]
> @wajihfabernovel Are you still interested in getting this over the finish line or do you want someone else to take over?

Yeah sure ! it is just that i am full focus in another project so I didn't have time to do it but i will come to it ASAP

**Comment by nialloulton** [comment]
@carlosagostini @wajihfabernovel i think my comments give the edits that it needs I think too to make it generic and fully flexible too. Hopefully this helps

**Comment by cetagostini-wise** [comment]
@ricardoV94 @nialloulton @juanitorduz @wd60622 

I'm addressing this PR in #632 with the new refactoring, allowing custom constraints. I'll suggest maybe close this temporarily because is very outdated. What do you think?

**Comment by juanitorduz** [comment]
> @ricardoV94 @nialloulton @juanitorduz @wd60622
> 
> I'm addressing this PR in #632 with the new refactoring, allowing custom constraints. I'll suggest maybe close this temporarily because is very outdated. What do you think?

Great! Let's come back to this one once you have merged #632 :)

**Comment by cetagostini** [comment]
Hey @juanitorduz 

Should be close this PR?

Currently we can import the Optimizer from the pymc package and replace the constraint. E.g:

```python
optimizer = BudgetOptimizer(
**kwargs
)

emissions_constraint = {
'type': 'ineq', 'fun': lambda x: max_emissions - sum(x[i]*emissions_per_channel[channels[i]] for i in range(len(x)))
}

optimizer.allocate_budget(
total_budget=max_emissions,
custom_constraints = emissions_constraint
)
```

Unless, exist another pain point. This should be solve!

**Comment by juanitorduz** [comment]
is that ok @wajihfabernovel ?

**Comment by wajihfabernovel** [comment]
hey, totally agree ! thanks

**Pull request closed without merging**
