### PR TITLE
MMM Notebook: fix z values which should be x

### PR DESCRIPTION
**Pull request by juanitorduz**
Closes https://github.com/pymc-labs/pymc-marketing/issues/137

Improve mmm example notation.

### CODE REVIEW

**Comment by juanitorduz** [comment]
<p>You are right (again hehe), fixed in https://github.com/pymc-labs/pymc-marketing/pull/138/commits/65bba41aa592735909c9692faf1fe4ac03c13e25</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/138/discussion/#comment-1411434667'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
@ricardoV94 it seems that the link checks are failing because some files in the `clv` module.

**Comment by juanitorduz** [comment]
<p>thanks! fixed in https://github.com/pymc-labs/pymc-marketing/pull/138/commits/9ce418f52c5e921e8033ef65ebd77ee0693bc225</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/138/discussion/#comment-1412314514'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by cluhmann — APPROVED** [review]
LTGM

**Pull request merged**
