### PR TITLE
Fix related to column renaming after aggregating test frequency

### LINKED ISSUE #688: bug in clv.utils.rfm_train_test_split()
When attempting to use the clv.utils.rfm_train_test_split() function, I ran into the following error:
KeyError: 'customer_id'
After testing it again with publicly available data (the online retail data from uci), I got the same error. Looking at the code, I believe it is being introduced by lines 565-567:
`    test_rfm_data = test_rfm_data.rename(
        columns={"id": "customer_id", "date": "test_frequency"}
    )`
where "id" and "date" should instead be customer_id_col and datetime_col. As is, if your id col and date col are not named exactly "id" and "date", they will not be renamed properly, which causes the error when the code then attempts to merge with the monetary value (lines 579-584).
If a monetary_value is not provided, then the error occurs later in lines 589-591 when it tries to merge back to the training_rfm_data.

How to reproduce error:
use clv.utils.rfm_train_test_split() with dataset that does not have the customer_id column explicitly named "customer_id" and the date column not explicitly named "date".

### PR DESCRIPTION
**Pull request by IvanUgrin**
## Description

This fix addresses a problem where the expected output of the "create dataframe with customer_id and test_frequency columns" operation outputs the columns with their originating names rather than the hardcoded "id" and "date" names. To properly rename the column names we need the column name parameters of the user of the function. Maybe you missed out the bug if you were testing with id and date column names.

## Related Issue

- [ ] Closes #688 
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [x] CLV

## Type of change

- [ ] New feature / enhancement
- [x] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--698.org.readthedocs.build/en/698/

### CODE REVIEW

**Comment by wd60622** [comment]
Hi @IvanUgrin 
Thanks for making this change. Can you write a test please 🙏

**Comment by ColtAllen** [comment]
This is such a quick fix, I hope you don't mind that I included it in https://github.com/pymc-labs/pymc-marketing/pull/680.

**Review by ColtAllen — APPROVED** [review]

**Comment by IvanUgrin** [comment]
Thanks! :) Keep up the good work! :)

**Comment by wd60622** [comment]
> Thanks! :) Keep up the good work! :)

Thanks for making the edit, @IvanUgrin !

**Pull request merged**
