### PR TITLE
Prior Parameter Distribution and Transform Visuals + Adstock Weighting and Contribution Visuals (Draft)

### PR DESCRIPTION
**Pull request by eirikbaekkelund**
## Description
Additional functionalities serving to help the users specify their priors. This includes functions to:
1. Explore the priors across channels
2. See the effect of the adstock- and saturation transforms across channels
3. Compare the adstocked contribution with the direct contribution curve

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
   (some functions in `delayed_saturated_mmm.py` might need to be checked.
- [ ] Included tests that prove the fix is effective or that the new feature works
   (have done some here, but not an exhaustive list of tests)
- [ ] Added necessary documentation (docstrings and/or example notebooks)
   (only modified the `mmm_example.ipynb` file to show functionality. Would either need a prior predictive notebook or create an additional section in the file with more detailed description and appriopriate headers + placement.
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes) 

Sorry, but the commits are a bit all over the place 🙈 

## Modules affected
- [x] MMM
- [ ] CLV

## Type of change
- [x] New feature / enhancement
- [ ] Bug fix
- [x] Documentation (A maybe here)
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--477.org.readthedocs.build/en/477/

### CODE REVIEW

**Comment by juanitorduz** [comment]
Thank you @eirikbaekkelund ! I will check this one in the upcoming weeks :)

**Comment by juanitorduz** [comment]
Why do we have so many commits from previous PRs/ Maybe you try rebasing?

**Comment by wd60622** [comment]
Hi @eirikbaekkelund 
Is this something that you are still interested in?

**Comment by eirikbaekkelund** [comment]
sure, can get it done within the next 2-3 weeks i think with current availability

**Comment by eirikbaekkelund** [comment]
still of interest for you guys @wd60622 @nialloulton @juanitorduz ?

**Comment by wd60622** [comment]
> still of interest for you guys @wd60622 @nialloulton @juanitorduz ?

Hi @eirikbaekkelund 
If you find it useful then I think it will be a great addition!
We did do a large refactor of the media transformations to each be a class themselves and no longer coupled with the MMM instance. i.e. media function agnostic MMM.  
Because of these large changes, you will at least have to do a rebase or restart with these changes. 
[Here](https://www.pymc-marketing.io/en/latest/notebooks/mmm/mmm_components.html) is an overview of the new class functionality which might be related to your edits. I am not familiar with your changes and would have to take a deeper look. Maybe you can make sense of what might still be missing. 
If you share the produced curves from these edits, it might be easier to see and compare

**Comment by wd60622** [comment]
Hi @eirikbaekkelund, still interested in this issue? If you are short on time, would you mind creating an issue for this feature? If you have a visual of what you are looking for, that would be helpful.

**Comment by eirikbaekkelund** [comment]
Hey @wd60622,

Apologies for the delayed response. I've been juggling a lot at work for some months, but I'm hoping to revisit this PR over the weekend. I'll need to familiarize myself with the latest updates to the library and clean up the boilerplate code.

I'm curious about your thoughts on creating a Streamlit app (similar to Desmos). If you're interested, let's schedule a quick call once I've made some progress.

**Comment by wd60622** [comment]
I will close this PR as it has become stale. Thanks for the work here. I will create some issues from it if others are interested!

**Pull request closed without merging**
