### PR TITLE
Add prior predictive example notebook

### PR DESCRIPTION
**Pull request by juanitorduz**
- Add prior predictive plot.
- Fix the double scaling bug.
- Typo from https://github.com/pymc-labs/pymc-marketing/pull/784

----
📚 Documentation preview 📚: https://pymc-marketing--787.org.readthedocs.build/en/787/

### CODE REVIEW

**Comment by juanitorduz** [comment]
When adding the prior-predictive step, the processing is wrong:

image

**Comment by wd60622** [comment]
Would the self.y be getting scaled twice? 
If you remove the sample_prior_predictive lines, this doesn't happen, right?

**Comment by juanitorduz** [comment]
The bug was fixed in https://github.com/pymc-labs/pymc-marketing/pull/787/commits/b765b38c89fb2606df90c5aada6c84519e990733

**Comment by wd60622** [comment]
Is it then the combination of `build_model` and `_data_setter`? As the `sample_posterior_predictive` method will call `_data_setter` but not the `build_model`...

**Review by wd60622 — APPROVED** [review]
Notebook looks good! Just question but not a blocker

**Comment by juanitorduz** [comment]
> Is it then the combination of `build_model` and `_data_setter`? As the `sample_posterior_predictive` method will call `_data_setter` but not the `build_model`...

I think we need to take a detailed look at how this is happening and that is why I created the issue above 😬. Let me merge this one and then work on the other issue.

**Pull request merged**
