### PR TITLE
Optimisation in customer_lifetime_value when discount_rate == 0

### PR DESCRIPTION
**Pull request by vincent-grosbois**
Optimisation in customer_lifetime_value when discount_rate == 0

closes https://github.com/pymc-labs/pymc-marketing/issues/467

----
📚 Documentation preview 📚: https://pymc-marketing--468.org.readthedocs.build/en/468/

### CODE REVIEW

**Review by vincent-grosbois — COMMENTED** [review]
whitespace

**Review by ricardoV94 — COMMENTED** [review]
Hi @vincent-grosbois, thanks for the PR. If it's this simple, that's great.

Can you add a test? Perhaps you can compute the quantity with discount rate == 0, before the PR change, and then hardcode the results and ensure it indeed comes out the same after the changes.

**Comment by vincent-grosbois** [comment]
I think there are some tests here :
https://github.com/pymc-labs/pymc-marketing/blob/2e826a9a97159c032081fac764591b0d04bd3929/tests/clv/test_utils.py#L150
which shows that nothing should have changed (because it's compared against some evaluations when discount_rate == 1, and this one didn't change)

**Comment by ricardoV94** [comment]
Great we already tested the zero case so we're good

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Thanks for the contribution!

**Pull request merged**
