### PR TITLE
Update resources page

### PR DESCRIPTION
**Pull request by juanitorduz**
Add recent resources. Let's try to keep this up to date. It is also a great sharable link to provide information about the project.

----
📚 Documentation preview 📚: https://pymc-marketing--539.org.readthedocs.build/en/539/

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]
Are the descriptions too verbose perhaps?

**Comment by juanitorduz** [comment]
> Are the descriptions too verbose perhaps?

I took it from the video descriptions from YouTube ... I am assuming this landing page is for someone new to the project, and that is why I included all the info ... should I trim it before merging :) ?

**Comment by ricardoV94** [comment]
As you prefer, I just raised the question because I didn't have a clear preference.

**Comment by juanitorduz** [comment]
Thanks! In this case, let me merge this one and wait for feedback 🤗

**Pull request merged**
