### PR TITLE
Draft: feature/setup doctests

### LINKED ISSUE #578: Run example code in doc strings in CI
We have quite some examples in doc strings which we currently don't run. When we change things they easily break and we don't notice. There is some tooling but not sure how to do that.

### PR DESCRIPTION
**Pull request by MuradKhalil**
## Description

- added a make command to run code in docstrings

## Related Issue

- [x] Closes #578 
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--869.org.readthedocs.build/en/869/

### CODE REVIEW

**Comment by MuradKhalil** [comment]
TODO: add this check to CI

**Comment by wd60622** [comment]
This will be awesome. Thanks for getting this started!

I'm not familiar with the tool. Is this an additional install? 

> TODO: add this check to CI

Might be good to run in parallel with other tests. WDYT?

**Comment by wd60622** [comment]
Hi @MuradKhalil 
Are you still interested in working on this? If not, I can make some issues for this

**Comment by MuradKhalil** [comment]
Hi @wd60622. I don't think I will be able to work on this again any time soon

**Comment by wd60622** [comment]
> Hi @wd60622. I don't think I will be able to work on this again any time soon

All good. Thank you for your work here. I will close and make some references to it in issues! Thanks again

**Pull request closed without merging**
