### PR TITLE
 Fix Visual for hill_saturation function (Issue #851 )

### PR DESCRIPTION
**Pull request by PatrickRobotham**
----
📚 Documentation preview 📚: https://pymc-marketing--857.org.readthedocs.build/en/857/

### CODE REVIEW

**Comment by PatrickRobotham** [comment]
Addresses issue https://github.com/pymc-labs/pymc-marketing/issues/851

**Comment by wd60622** [comment]
Doesnt seem to show up. Maybe there is an issue with the spacing
https://pymc-marketing--857.org.readthedocs.build/en/857/api/generated/pymc_marketing.mmm.transformers.hill_saturation.html#pymc_marketing.mmm.transformers.hill_saturation

**Comment by PatrickRobotham** [comment]
Thanks for pointing this out. I forgot to clean the docs in my local testing. I hope this latest commit solves it.

**Review by wd60622 — COMMENTED** [review]
Thanks @PatrickRobotham.
Looks good! 

One adjustment now that I see the plots. 
Could you use 
fig, axes = plt.subplots(..., sharey=True)
Think that this would be better for showing the `sigma` parameter differences. 
We don't need the ylabel on axes[1:] as well then

**Review by wd60622 — APPROVED** [review]
Looks great! Will let the ci cd run then will merge in

**Comment by wd60622** [comment]
Thanks @PatrickRobotham !

**Pull request merged**
