### PR TITLE
Break test suite into smaller sections

### PR DESCRIPTION
**Pull request by wd60622**
## Description

Inspired by pytensor

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--1275.org.readthedocs.build/en/1275/

### CODE REVIEW

**Comment by wd60622** [comment]
Before: https://github.com/pymc-labs/pymc-marketing/actions/runs/12319328576/usage
After: https://github.com/pymc-labs/pymc-marketing/actions/runs/12319717755/usage?pr=1275

Bottlenecked by the slow tests which took 23 minutes in this run

**Comment by wd60622** [comment]
including File breakdown tests: https://github.com/pymc-labs/pymc-marketing/actions/runs/12320439851/usage

**Review by juanitorduz — APPROVED** [review]
yay!

**Comment by wd60622** [comment]
One more split.. Might get it under 10 minutes 🛩️

**Comment by wd60622** [comment]
too hopefully. Under 15 minutes

**Comment by wd60622** [comment]
Breaking down MMM into two : https://github.com/pymc-labs/pymc-marketing/actions/runs/12320717960/usage

**Comment by wd60622** [comment]
Rearranging the files in the mmm group : https://github.com/pymc-labs/pymc-marketing/actions/runs/12321376436/usage

**Comment by wd60622** [comment]
27 minutes -> 13 minutes

Good enough?

**Comment by juanitorduz** [comment]
yes! @wd60622 feel free to merge!

**Pull request merged**
