### PR TITLE
Add to documentation feature comparison

### LINKED ISSUE #538: Add budget optimizer as feature in docs
https://www.pymc-marketing.io/en/stable/guide/mmm/comparison.html

### PR DESCRIPTION
**Pull request by wd60622**
## Description

The current MMM features were outdated and add some additional rows for o

Still think we should discuss if this should be included at all as it might be hard to maintain

## Related Issue

- [ ] Closes #538 
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [x] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--550.org.readthedocs.build/en/550/

### CODE REVIEW

**Comment by wd60622** [comment]
New table: 
https://pymc-marketing--550.org.readthedocs.build/en/550/guide/mmm/comparison.html
new-table

**Review by juanitorduz — APPROVED** [review]
LGTM 👍

**Comment by juanitorduz** [comment]
Actually, Recast does have time-varying coefficients (they have said so a couple of times). Hence I will mark it as well instead of “?”

**Comment by juanitorduz** [comment]
I would also add a “is unit-tested” 😂 as Robyn does not have a single test. Red flag 🚩

**Comment by juanitorduz** [comment]
All tested except Recast which is not public, so maybe “?”

**Comment by cetagostini** [comment]
Hey @juanitorduz are you sure about the TVP? I understand based on what they mentioned here, they have it. https://mmm-hub.slack.com/archives/C05RDDE1GUB/p1708474546559629?thread_ts=1707851321.022429&cid=C05RDDE1GUB

**Comment by juanitorduz** [comment]
Yes! I agree! This is what I meant above. They do have time-varying coefficients in some flavour. My last comment was about unit-tests :)

**Comment by ulfaslak** [comment]
Pretty sure they do. Was in a sales call with them some months ago and the guy made it very clear that they had TVP.

**Comment by wd60622** [comment]
Here is the updated table

latest-features

**Comment by juanitorduz** [comment]
Looks great!

**Review by juanitorduz — APPROVED** [review]

**Review by ulfaslak — APPROVED** [review]

**Comment by juanitorduz** [comment]
Done! Thanks @wd60622 !

**Comment by ricardoV94** [comment]
@juanitorduz This PR should probably have been squashed merged, no point in having 6 dirty commits in the git history

**Comment by ricardoV94** [comment]
Better to let it stay as is. I was just flagging it in case it wasn't a one time slip. I also do it now and then

**Comment by juanitorduz** [comment]
Ok! Thanks for the remainder anyway 💪

**Pull request merged**
