### PR TITLE
Ignore E501 Globaly (fix lint)

### PR DESCRIPTION
**Pull request by juanitorduz**
fix lint

### CODE REVIEW

**Comment by lucianopaz** [comment]
I think that it’s better to ignore E501 throughout the entire code base and just rely on black to automatically reformat code relevant lines. Docstrings and comments shouldn’t have any bearing on the line length lint test

**Comment by OriolAbril** [comment]
I think I could also update that to use multi-line math and not need to ignore the line length check, not sure what option do you prefer

**Comment by juanitorduz** [comment]
I do not have any strong opinion. Maybe we want our doc-strings to be quite complete with formulas and explanations where we might not want to be limited by this lint checker. Again, no strong opinion :)

**Comment by lucianopaz** [comment]
> I think I could also update that to use multi-line math and not need to ignore the line length check, not sure what option do you prefer

I think that the best is to disable that flag globally, but you could also use multi line math in the docstrings

**Comment by juanitorduz** [comment]
so shall we merge as it is :) ?

**Review by lucianopaz — APPROVED** [review]

**Pull request merged**
