### PR TITLE
Run slow tests in CI

### LINKED ISSUE #308: Run `slow` tests on CI
The tests marked as `pytest.mark.slow` are currently not running in the CI. We should consider running them, but have to make sure CI runtime doesn't balloon. If it does, we can perhaps split the tests into more jobs.

### PR DESCRIPTION
**Pull request by ricardoV94**
## Description

Adds a separate CI job that runs only the slow tests. The reason for the split is that these tests won't run locally by default, and on the CI they will run separately so that the faster tests can act as a faster smoke test 

## Related Issue

- [x] Closes #308 
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--555.org.readthedocs.build/en/555/

### CODE REVIEW

**Comment by ricardoV94** [comment]
Only the GammaGamma slow test seems to fail: https://github.com/pymc-labs/pymc-marketing/actions/runs/8110804909/job/22168800146?pr=555#step:4:782

Perhaps @ColtAllen you could take a look sometime?

**Comment by ricardoV94** [comment]
The GammaGamma convergence failure may be due to the strange test config that was being used since the ModelBuilder refactoring

**Comment by ColtAllen** [comment]
> The GammaGamma convergence failure may be due to the strange test config that was being used since the ModelBuilder refactoring

I'm not sure why this config is being specified in the test either. Can it just be ran with the default config?

**Comment by ricardoV94** [comment]
Yeah I changed it but the HalfFlat doesn't converge which may be fair. I'll give slightly better priors although the original test had HalfFlat priors I think

**Pull request merged**
