### PR TITLE
Remove unnecessary NonImplemented errors from abstract methods

### PR DESCRIPTION
**Pull request by juanitorduz**
We want to have a more precise metric of code coverage.

----
📚 Documentation preview 📚: https://pymc-marketing--662.org.readthedocs.build/en/662/

### CODE REVIEW

**Comment by wd60622** [comment]
Which lines do you have in mind? Looking at the cov report, NotImplementedError seems to be used in various ways. Maybe alternative errors can be raised

**Comment by juanitorduz** [comment]
It is indeed for the abstract methods 😄. Some while ago I wrote trivial tests for them so that the coverage did not go down because if this. Ricardo pointed me out this was an overkill. So shall we maybe do not raise any error (I did not in now it was raised automatically).

**Comment by wd60622** [comment]
Well can the function body be removed for abstract methods?

**Review by wd60622 — APPROVED** [review]
LGTM!

**Pull request merged**
