### PR TITLE
Add bolt's journey with pymc-marketing

### PR DESCRIPTION
**Pull request by SangamSwadiK**
Add Bolt's journey with PyMC-marketing on pymc-marketing.io

----
:books: Documentation preview :books:: https://pymc-marketing--359.org.readthedocs.build/en/359/

### CODE REVIEW

**Comment by ricardoV94** [comment]
I think we should put this in `mmm #resources` like in this PR? https://github.com/pymc-labs/pymc-marketing/pull/249

**Comment by ricardoV94** [comment]
> I think we should do both.

If we want to add it on the index page, we should add a new section? Maybe something along the lines of `Who is using PyMC-Marketing`?

**Comment by twiecki** [comment]
@SangamSwadiK Can you make those changes?

**Comment by twiecki** [comment]
thanks!

**Pull request merged**
