### PR TITLE
Add CLV `plot_expected_purchases_ppc`

### PR DESCRIPTION
**Pull request by ColtAllen**
## Description

This PR adds a plotting function for prior and posterior predictive checks of customer purchases.

`plot_expected_purchases_ppc(model, ppc='prior');`

image

`plot_expected_purchases_ppc(model, ppc='posterior');`

image

I've created an issue for adding HDI ranges to these plots, and while revising the ParetoNBD notebook also removed a model file that was being created.

## Related Issue

- [x] Closes  https://github.com/pymc-labs/pymc-marketing/issues/278
- [x] Related to  https://github.com/pymc-labs/pymc-marketing/issues/1155, https://github.com/pymc-labs/pymc-marketing/issues/326, https://github.com/pymc-labs/pymc-marketing/issues/1223

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [x] CLV

## Type of change

- [x] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--1222.org.readthedocs.build/en/1222/

### CODE REVIEW

**Comment by ColtAllen** [comment]
Three extraneous tests for the `MMM` and `Prior` modules are failing in the CI.

**Review by juanitorduz — APPROVED** [review]
Great! 🚀

**Comment by juanitorduz** [comment]
@ColtAllen we have a fix for the mmm tests failing in https://github.com/pymc-labs/pymc-marketing/pull/1240. You need to rebase and then we can merge (there are some lint fixes as well)

**Comment by juanitorduz** [comment]
pre-commit.ci autofix

**Pull request merged**
