### PR TITLE
fix lint 🙈 

### PR DESCRIPTION
**Pull request by juanitorduz**
When I rebased and merged https://github.com/pymc-labs/pymc-marketing/pull/138 the lint problem persists. I hope this fix it :)

### CODE REVIEW

**Comment by ricardoV94** [comment]
Is your pylint more strict than ours/CI? Mine is not deleting single empty lines. Maybe it's a new version?

**Comment by juanitorduz** [comment]
We are not using `pylint` right? In the make file:
```
check_lint:
	pip install -r lint-requirements.txt
	flake8 .
	isort --check-only .
	black --diff --check --fast .
```
😄

**Comment by ricardoV94** [comment]
I meant whatever lint was in pre-commit, just defaulted to thinking it was pylint

**Comment by juanitorduz** [comment]
I created a conda env from scratch and it seems to be running in the ci/cd as well. One thing I have noticed is that we are not specifying the revisions (versions) of the lint-packages.

**Comment by ricardoV94** [comment]
Yeah I suspect it's a new behavior

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
We should treat the CI as the ground truth though, otherwise there will be inconsistencies soon enough again

**Comment by juanitorduz** [comment]
I will create an issue

**Pull request merged**
