### PR TITLE
Fallback to defaults in `adstock|saturation_from_dict`

### LINKED ISSUE #950: Assume default priors for `adstock_from_dict` and `saturation_from_dict` functions
These functions require the `priors` key in the dictionary. However, it might be convienient to assume default priors if the key is not present. This is especially useful when the user is not interested in specifying priors.

Setup: 

```python
from pymc_marketing.mmm import saturation_from_dict
```

Before: 

```python
saturation_from_dict({
    "lookup_name": "hill", 
    "priors": {...},
})
```

After

```python
saturation_from_dict({"lookup_name": "hill"})
```

### PR DESCRIPTION
**Pull request by PabloRoque**
## Related Issue

- [x] Closes #950
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [x] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--955.org.readthedocs.build/en/955/

### CODE REVIEW

**Comment by PabloRoque** [comment]
Hey, sorry that I had to open 3 separate PRs for the same functionality. 
Working on a fork is not as flexible sometimes. 

This PR should be good to review

**Comment by wd60622** [comment]
> Hey, sorry that I had to open 3 separate PRs for the same functionality. Working on a fork is not as flexible sometimes.
> 
> This PR should be good to review

All good! Thanks for taking the issue!

**Comment by wd60622** [comment]
pre-commit.ci autofix

**Comment by wd60622** [comment]
Thanks @PabloRoque !

**Pull request merged**
