### PR TITLE
MMM: fix quickstart instructions not working 

### LINKED ISSUE #384: Quickstart instructions give errors
Extra bracket on MMM quickstart instructions, also think it should be model = mmm.DelayedSaturatedMMM()?

Also when running fit model, get this error "cannot reindex on an axis with duplicate labels"

### PR DESCRIPTION
**Pull request by MarkusSagen**
Updated the MMM quickstart instructions and data for the MMM quickstart on the pymc-marketing start page

Fixes #384 Quickstart instructions give errors

----
:books: Documentation preview :books:: https://pymc-marketing--403.org.readthedocs.build/en/403/

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @MarkusSagen, this is a great contribution!

**Comment by MarkusSagen** [comment]
Happy to give back to the community and all the great work the team is doing!

Are there any other issues that I could help tackle?

**Comment by twiecki** [comment]
Yes, much appreciated. This could be a good place to start: https://github.com/pymc-labs/pymc-marketing/labels/good%20first%20issue

**Comment by MarkusSagen** [comment]
Thanks! Will take a look

**Pull request merged**
