### PR TITLE
Support use of `ParetoNBDModel` in `customer_lifetime_value`

### PR DESCRIPTION
**Pull request by ColtAllen**
## Description

This PR adds a hotfix so that `ParetoNBDModel` can be used in the `customer_lifetime_value` utility. [A more comprehensive fix](https://github.com/pymc-labs/pymc-marketing/pull/506) would involve breaking API changes , and I'd rather not hold up the next release any longer.

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [x] CLV

## Type of change

- [ ] New feature / enhancement
- [x] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--512.org.readthedocs.build/en/512/

### CODE REVIEW

**Comment by ColtAllen** [comment]
`tests/clv/test_utils.py::TestCustomerLifetimeValue::test_customer_lifetime_value_with_known_values` is failing despite no changes made from `main`.

**Comment by ricardoV94** [comment]
@ColtAllen Let me know if the changes look good. Note that I forced push, so you will need to get the remote branch if you want to do changes locally

**Comment by ColtAllen** [comment]
@ricardoV94 I think everything's good to go for the hotfix. I'll get an issue created this week for the API discussion.

**Comment by ricardoV94** [comment]
Failing test is unrelated: #516 

Merging this one

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
