### PR TITLE
Add more content to the BG/NBD Notebook

### PR DESCRIPTION
**Pull request by juanitorduz**
Colses https://github.com/pymc-labs/pymc-marketing/issues/225

I suggest adding more info about the model, plots, and an example of how to use it in practice. For an application, I show how to estimate the probabilities of being active over time at customer level.

Feedback is welcome!

----
📚 Documentation preview 📚: https://pymc-marketing--571.org.readthedocs.build/en/571/

### CODE REVIEW

**Comment by juanitorduz** [comment]
<p>I did nit know! Thanks for the remark! I will remove it!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-1983343705'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I think the output is not as nice as the data from pymc models ... its a bit too verbose </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-1983343731'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ColtAllen** [comment]
<p>It's important to mention these plots assume no future purchases. I tried applying this concept once and ultimately could not because frequent, reliable customers were being flagged as no longer active. The <code>ParetoNBDModel</code> does not have this issue.</p><p> </p><p>This is more about understanding the model though, so we can still include the plots to compare a frequent buyer to an infrequent one to illustrate the no-purchase assumption.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-1983343749'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Great point! I will add this into the plot. My intention is to tease what yo could do with the model .... </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-1983343749'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wd60622** [comment]
<p>My comment was just make some fake customers and hold some more of the values constant. For instance, make T some value for all customers and vary only recency and frequency. </p><p>Additional, if you hold T and frequency constant and only vary recency in order to deep dive in hold the model is reacting</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-1983343749'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>build model followed by printing it (by just including model at the last line of cell) is a nice way to show how the model looks like internally though</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-1983343705'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wd60622** [comment]
<p>Might be good to put in separate cells then. Lumping all of the command together might suggest that that is required for the API</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-1983343705'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
@wd60622 @ColtAllen I added some changes based on your feedback 🙏 . Let me know what you think :)

**Comment by ColtAllen** [comment]
Good work! Most of my comments in the ReviewNB are minor styling and clean up remarks, but there is some additional content which may be worth adding.

**Comment by juanitorduz** [comment]
<p>+1 </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037765975'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Good point!</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766017'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I re-wrote it so that (hopefully) is clearer now </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>+1</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766123'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Let me skip this for now as i wanna keep this relative simple. I agree is a great point to maybe we could have a prior sensitivity analysis notebook :)</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766140'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Added a section!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766162'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
Thanks, @ColtAllen. I think I addressed all of the comments except the pytensor warnings I am trying to remove. In particular, I added another section on the applications (expected number of purchases). Let me know what you think about this version :)

**Comment by ColtAllen** [comment]
<p>The sentence as a whole just seems unnecessary. We could probably begin with "The BG/NBD model is. . ." but it's not a dealbreaker in either case.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>hahah sorry! I thought you were talking about the last paragraph ! Yes! You are right!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Thanks for the input! </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2038321546'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ColtAllen** [comment]
<p>Just a style preference, but <code>CLVModel</code>s is awkward looking. Maybe change to "CLV models such as <code>BetaGeoModel</code> ..."   </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766140'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Thanks! fixed!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2039938738'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Thanks!</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2039938766'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Combining it make the output look confusing ....</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766102'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Agree! Fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/571/discussion/#comment-2037766140'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
Thanks for pointing out the typos @ColtAllen 🙏

**Review by ColtAllen — APPROVED** [review]
A few unresolved remarks in ReviewNB, but they're just optional formatting suggestions. Awesome job!

**Pull request merged**
