### PR TITLE
MMM Component Notebook

### PR DESCRIPTION
**Pull request by wd60622**
## Description

Making some more advance resources for the model components that are not available due to #632 

## Related Issue

- [ ] Closes #
- [x] Related to #711 

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Modules affected

- [ ] MMM
- [ ] CLV

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc-marketing--748.org.readthedocs.build/en/748/

### CODE REVIEW

**Comment by cetagostini** [comment]
Really amazing work with this new document 🔥

**Comment by wd60622** [comment]
<p>Sure thing. I can do that for displaying purposes. The thing is that it is no longer a DataFrame in long format but a xarray </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/748/discussion/#comment-2171892711'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
@wd60622 This is really remarkable! The long PR you and @cetagostini made is making these docs and new features come "for free" 🚀

**Comment by wd60622** [comment]
<p>perfect. Good tip</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/748/discussion/#comment-2174252884'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by wd60622** [comment]
<p>call it done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/pymc-marketing/pull/748/discussion/#comment-2174252860'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by juanitorduz — APPROVED** [review]
Thanks @wd60622 ! It looks great!

**Pull request merged**
