### PR TITLE
Use MaxAbsScaler instead of MinMaxScaler for Target MMM

### PR DESCRIPTION
**Pull request by juanitorduz**
Use MaxAbsScaler instead of MinMaxScaler for Target MMM. This is important when computing ROAS. It also makes the transformation (and inverse transformations easier)

### CODE REVIEW

**Comment by cluhmann** [comment]
Haven't tested, but it looks like this removes `compute_channel_contribution_original_scale()` entirely.  Was that intentional?  That method is currently used in various places including in the `plot_contribution_curves()` method and directly used in the MMM example notebook.  Doesn't `compute_channel_contribution_original_scale()` just need to be revised to use the new `MaxAbsScaleTarget`? If so, I'm happy to do that.

**Comment by juanitorduz** [comment]
I remove it because it's already implemented in the base class. So the example notebook should still work (would you mind testing just to double check 🤗)

**Comment by cluhmann** [comment]
Yes. I had missed the method in the base class (now I remember you saying this yesterday).

**Comment by ricardoV94** [comment]
Does this impart the MMM example?

**Comment by juanitorduz** [comment]
I tested it and it was ok! I think @cluhmann also tested it right ? (In the example the min values are zero anyway)

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
