### PR TITLE
Bump minimal dependency PyMC >= 5.16

### PR DESCRIPTION
**Pull request by juanitorduz**
Closes https://github.com/pymc-labs/pymc-marketing/issues/726

----
📚 Documentation preview 📚: https://pymc-marketing--1241.org.readthedocs.build/en/1241/

### CODE REVIEW

**Comment by wd60622** [comment]
What's the reason for the upper bound at 5.19.0?

**Comment by juanitorduz** [comment]
> What's the reason for the upper bound at 5.19.0?

Not strong opinions and we can remove it. I was thinking if 5.19.0 has other breaking changes that users are not faced with cryptic error messages. We can also make pymc-marketing releases more often that support every pymc major version update. WDYT?

**Comment by wd60622** [comment]
> Not strong opinions and we can remove it. I was thinking if 5.19.0 has other breaking changes that users are not faced with cryptic error messages. We can also make pymc-marketing releases more often that support every pymc major version update. WDYT?

That'd be ideal so new pytensor can be used

**Comment by wd60622** [comment]
And wouldn't the test suite catch if the latest version of pymc is not working?

**Comment by juanitorduz** [comment]
Yes, but imagine another package or model in prod using pymc marketing. If they do not pin for a potential pymc breaking change then it will break their pipelines. Whereas if we have this is just a much more conservative approach. TBH, not strong opinion but this might motivate us to sync pathc releases with pymc

**Comment by juanitorduz** [comment]
See https://github.com/pymc-labs/pymc-marketing/pull/1269

**Pull request closed without merging**
